//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string AccountLink {
            get {
                return ResourceManager.GetString("AccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string CCName {
            get {
                return ResourceManager.GetString("CCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Price.
        /// </summary>
        public static string DailyPrice {
            get {
                return ResourceManager.GetString("DailyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals.
        /// </summary>
        public static string DealsLink {
            get {
                return ResourceManager.GetString("DealsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Doors.
        /// </summary>
        public static string DoorsCount {
            get {
                return ResourceManager.GetString("DoorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to € off.
        /// </summary>
        public static string FixedReduc {
            get {
                return ResourceManager.GetString("FixedReduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet.
        /// </summary>
        public static string FleetLink {
            get {
                return ResourceManager.GetString("FleetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Fuel.
        /// </summary>
        public static string FuelName {
            get {
                return ResourceManager.GetString("FuelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up Place.
        /// </summary>
        public static string lblPickupPlace {
            get {
                return ResourceManager.GetString("lblPickupPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string MakeName {
            get {
                return ResourceManager.GetString("MakeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Ndays {
            get {
                return ResourceManager.GetString("Ndays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Search.
        /// </summary>
        public static string NewSearch {
            get {
                return ResourceManager.GetString("NewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office_Name {
            get {
                return ResourceManager.GetString("Office_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % off.
        /// </summary>
        public static string PercentReduc {
            get {
                return ResourceManager.GetString("PercentReduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Pay.
        /// </summary>
        public static string PriceToPay {
            get {
                return ResourceManager.GetString("PriceToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string PromoName {
            get {
                return ResourceManager.GetString("PromoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion (Total).
        /// </summary>
        public static string PromoTotal {
            get {
                return ResourceManager.GetString("PromoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent a Car.
        /// </summary>
        public static string RentLink {
            get {
                return ResourceManager.GetString("RentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent This Car.
        /// </summary>
        public static string RentThisLink {
            get {
                return ResourceManager.GetString("RentThisLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Vehicles.
        /// </summary>
        public static string SeeAllVehicles {
            get {
                return ResourceManager.GetString("SeeAllVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of doors.
        /// </summary>
        public static string SelectDoors {
            get {
                return ResourceManager.GetString("SelectDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the fuel type.
        /// </summary>
        public static string SelectFuel {
            get {
                return ResourceManager.GetString("SelectFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the make.
        /// </summary>
        public static string SelectMake {
            get {
                return ResourceManager.GetString("SelectMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the pick-up place.
        /// </summary>
        public static string SelectPlace {
            get {
                return ResourceManager.GetString("SelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Infos.
        /// </summary>
        public static string vDetailsLink {
            get {
                return ResourceManager.GetString("vDetailsLink", resourceCulture);
            }
        }
    }
}
